myProgram:test-subseq.o maxSeq.o
	gcc -o myProgram test-subseq.o maxSeq.o
test-subseq.o:test-subseq.c
	gcc -std=gnu99 -Wall -pedantic -Werror -c test-subseq.c 
maxSeq.o:maxSeq.c
	gcc -std=gnu99 -Wall -pedantic -Werror -c maxSeq.c
