##myshell: myshell.cpp myshell.h
##	g++ -ggdb3 -Wall -Werror -pedantic -o myshell myshell.cpp myshell.h


parse: parse.cpp
	g++ -ggdb3 -Wall -Werror -pedantic -o parse parse.cpp


clean:
##	rm myshell *~
	rm parse *~

