myshell: myshell.cpp
	g++ -ggdb3 -Wall -Werror -pedantic -o myshell myshell.cpp -std=gnu++11


parse: parse.cpp
	g++ -ggdb3 -Wall -Werror -pedantic -o parse parse.cpp -std=gnu++11


clean:
	rm myshell *~
	rm parse *~

