myShell: myshell.cpp
	g++ -ggdb3 -Wall -Werror -pedantic -o myShell myshell.cpp -std=gnu++11


parse: parse.cpp
	g++ -ggdb3 -Wall -Werror -pedantic -o parse parse.cpp -std=gnu++11


clean:
	rm myShell *~
	rm parse *~

